openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /reservations/{id}:
    get:
      tags:
      - reservation-controller
      operationId: getReservationById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReservationResponse'
    put:
      tags:
      - reservation-controller
      operationId: updateReservation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationRequest'
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "202":
          description: Accepted
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReservationResponse'
    delete:
      tags:
      - reservation-controller
      operationId: deleteReservation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "202":
          description: Accepted
  /devices/{id}:
    get:
      tags:
      - device-controller
      operationId: getDeviceById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DeviceDetailResponse'
    put:
      tags:
      - device-controller
      operationId: updateDevice
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
    delete:
      tags:
      - device-controller
      operationId: deleteDevice
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
  /reservations:
    get:
      tags:
      - reservation-controller
      operationId: getAllReservations
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageResponseReservationResponse'
    post:
      tags:
      - reservation-controller
      operationId: createReservation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationRequest'
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReservationResponse'
  /devices:
    get:
      tags:
      - device-controller
      operationId: getAllDevice
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageResponseDeviceResponse'
    post:
      tags:
      - device-controller
      operationId: createDevice
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
components:
  schemas:
    ReservationRequest:
      required:
      - deviceId
      - userId
      type: object
      properties:
        deviceId:
          type: string
        userId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    ReservationResponse:
      type: object
      properties:
        reservationId:
          type: string
        deviceId:
          type: string
        userId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    PageResponseReservationResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ReservationResponse'
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        totalItems:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
    DeviceResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    PageResponseDeviceResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/DeviceResponse'
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        totalItems:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
    DeviceDetailResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        reservations:
          $ref: '#/components/schemas/DeviceReservation'
        information:
          $ref: '#/components/schemas/DeviceInformation'
    DeviceInformation:
      type: object
      properties:
        technology:
          type: string
        bands:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    DeviceReservation:
      type: object
      properties:
        completedReservations:
          type: array
          items:
            $ref: '#/components/schemas/ReservationResponse'
        bookedReservations:
          type: array
          items:
            $ref: '#/components/schemas/ReservationResponse'
        isAvailable:
          type: boolean
